# Generated by Django 5.0.1 on 2024-01-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangoutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('google_pin', models.CharField(max_length=250)),
                ('emoji_icon', models.CharField(max_length=1)),
                ('votes', models.IntegerField()),
                ('tag', models.CharField(choices=[('FD', 'Food'), ('GM', 'Gaming'), ('RC', 'Recreation'), ('CH', 'Chill'), ('SP', 'Sports'), ('PD', 'Productive'), ('EV', 'Events'), ('ET', 'Entertainment'), ('OT', 'Others')], default='Others', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('is_offlines', models.BooleanField(default=False)),
                ('has_been_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HangoutEntryDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('google_pin', models.CharField(max_length=250)),
                ('emoji_icon', models.CharField(max_length=1)),
                ('votes', models.IntegerField()),
                ('tag', models.CharField(choices=[('FD', 'Food'), ('GM', 'Gaming'), ('RC', 'Recreation'), ('CH', 'Chill'), ('SP', 'Sports'), ('PD', 'Productive'), ('EV', 'Events'), ('ET', 'Entertainment'), ('OT', 'Others')], default='Others', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('is_offlines', models.BooleanField(default=False)),
                ('has_been_done', models.BooleanField(default=False)),
            ],
        ),
    ]
