# Generated by Django 5.0.1 on 2024-02-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hangoutentry',
            old_name='is_offlines',
            new_name='is_offline',
        ),
        migrations.RenameField(
            model_name='hangoutentrydev',
            old_name='is_offlines',
            new_name='is_offline',
        ),
        migrations.AlterField(
            model_name='hangoutentry',
            name='emoji_icon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hangoutentrydev',
            name='emoji_icon',
            field=models.CharField(max_length=100),
        ),
    ]
