import time

dummy_data = [
  {
    'name':'Mookata',
    'location': 'ang mo kio s11',
    'googlePin': 'https://google.com',
    'emojiIcon': '🥘',
    'votes': '5',
    'tag': 'FD',
    'createdAt': time.time(),
    'lastEdited': time.time(),
    'isOffline':True,
    'hasBeenDone': True,
  },
  {
    'name':'ping pong',
    'location': 'Yio chu kang stadium',
    'googlePin': 'https://google.com',
    'emojiIcon': '🏓',
    'votes': '8',
    'tag': 'SP',
    'createdAt': time.time(),
    'lastEdited': time.time(),
    'isOffline':True,
    'hasBeenDone': False,
  },
  {
    'name':'Play Civilisation',
    'location': 'ang mo kio s11',
    'googlePin': 'https://google.com',
    'emojiIcon': '🕹️',
    'votes': '6',
    'tag': 'GM',
    'createdAt': time.time(),
    'lastEdited': time.time(),
    'isOffline':False,
    'hasBeenDone': True,
  },
  {
    'name':'Play Beat Saber',
    'location': "An&Phong's house",
    'googlePin': 'https://google.com',
    'emojiIcon': '⚔️',
    'votes': '3',
    'tag': 'GM',
    'createdAt': time.time(),
    'lastEdited': time.time(),
    'isOffline':False,
    'hasBeenDone': False,
  },
]